#.travis.yml

sudo: required
dist: trusty
language: node_js
node_js:
  - '6.9'

#branches:
#  only:
#    - master

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install
  - ng build

script:
  - ng test --code-coverage --single-run
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
=======

before_script:
#  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
#  - firebase deploy --token $FIREBASE_TOKEN
